from estimator.dqn import DQN
from estimator.softdqn import SoftDQN
from estimator.doubledqn import DoubleDQN
from estimator.avedqn import AveDQN
from estimator.distdqn import DistDQN
from estimator.pg import PG
from estimator.trpo import TRPO
from estimator.a2c import A2C
from estimator.ppo import PPO
from estimator.ddpg import DDPG
