from .dqn import DQN
from .softdqn import SoftDQN
from .doubledqn import DoubleDQN
from .avedqn import AveDQN
from .distdqn import DistDQN
from .pg import PG
from .trpo import TRPO
from .a2c import A2C
from .ppo import PPO
from .ddpg import DDPG
from .learner import Learner
